#!/usr/bin/env node
// Embeds the vendored Mermaid browser runtime (src/client/vendor/mermaid.min.js)
// into an importable module at src/client/mermaid.bundle.js exporting MERMAID_JS
// as a string. index.js serves that string at GET /vendor/mermaid.min.js and the
// spec page lazy-loads it on the first diagram, so the runtime travels inside the
// bundled cli.cjs / SEA binary and works fully offline. Committed to the repo so
// plain `node src/index.js` dev runs need no pre-build.
//
// The vendored dist is the official Mermaid release, pulled through Microsoft's
// internal PowerBIClients Azure Artifacts npm feed (never a public CDN) via
// `npm pack mermaid@<ver>` and extracting package/dist/mermaid.min.js.
//
// Usage: npm run build:mermaid

import { build } from "esbuild";
import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "src/client/vendor/mermaid.min.js");
const OUT = path.join(ROOT, "src/client/mermaid.bundle.js");

const js = fs.readFileSync(SRC, "utf8");
if (!js.includes('globalThis["mermaid"]')) {
  throw new Error("Vendored mermaid.min.js does not expose the mermaid global — wrong dist file?");
}

const module = `// AUTO-GENERATED by scripts/build-mermaid.js — do not edit by hand.
// Official Mermaid browser runtime, embedded as a string and served at
// /vendor/mermaid.min.js. Run \`npm run build:mermaid\` to regenerate from
// src/client/vendor/mermaid.min.js.
export const MERMAID_JS = ${JSON.stringify(js)};
`;

fs.writeFileSync(OUT, module);
const mb = (Buffer.byteLength(js) / (1024 * 1024)).toFixed(2);
console.log(`  \u2713 src/client/mermaid.bundle.js  (${mb} MB embedded mermaid runtime)`);

// Bundle the client-side view module (src/client/mermaid-view.js) into an
// embeddable IIFE at src/client/mermaid-view.bundle.js exporting MERMAID_VIEW_JS.
// It is inlined into the spec page, so it ships inside the SEA binary and works
// offline. mermaid-view.js does not self-init on import, so append the
// initMermaidView() call to the browser IIFE.
const VIEW_ENTRY = path.join(ROOT, "src/client/mermaid-view.js");
const VIEW_OUT = path.join(ROOT, "src/client/mermaid-view.bundle.js");

const viewResult = await build({
  entryPoints: [VIEW_ENTRY],
  bundle: true,
  format: "iife",
  globalName: "TippaniMermaidView",
  platform: "browser",
  target: "es2020",
  minify: true,
  write: false,
});

const viewJs = viewResult.outputFiles[0].text + "\nTippaniMermaidView.initMermaidView();\n";
const viewModule = `// AUTO-GENERATED by scripts/build-mermaid.js — do not edit by hand.
// Browser Mermaid-view bundle, inlined into the spec page. Run
// \`npm run build:mermaid\` to regenerate from src/client/mermaid-view.js.
export const MERMAID_VIEW_JS = ${JSON.stringify(viewJs)};
`;

fs.writeFileSync(VIEW_OUT, viewModule);
const vkb = (Buffer.byteLength(viewJs) / 1024).toFixed(0);
console.log(`  \u2713 src/client/mermaid-view.bundle.js  (${vkb} KB browser view bundle)`);

